### ISSUE TITLE
Support for env variables?

### ISSUE THREAD

**Issue by bartelemi** [qase-tms/gh-actions#5]
As Qase CLI supports environment variables for stuff like auth tokens, it would be nice if these actions would support that as well, instead of requiring token input.

**Comment by gibiw** [comment]
Hi @bartelemi! This is now supported in v1.2.

All actions now accept the `QASE_TESTOPS_API_TOKEN` environment variable as an alternative to the `token` input. You can set it once at the workflow or job level:

```yaml
env:
  QASE_TESTOPS_API_TOKEN: ${{ secrets.QASE_TOKEN }}

steps:
  - uses: qase-tms/gh-actions/run-create@v1
    with:
      project: CODE
      title: Test Run
  # ... no need to pass token to each action
```

If both the `token` input and the environment variable are provided, the input takes priority.

See #7 for details.
